resource_group_name         = "myrg01"
resource_group_location     = "East Us"
virtual_network_name        = "myvnet"
subnet_name                 = "mywebsub"
public_ip_name              = "mypip"
network_security_group_name = "mynsg"
network_interface_name      = "mynic"
linux_virtual_machine_name  = "myubuntu"
